service:
  name: supereleven-serverless

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  region: eu-west-1
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 60
  runtime: nodejs8.10

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/app/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
package:
  individually: true
  include:
    - .env
